import DemoObserver from "./Observer";
import DemoAdapter from "./Adapter/index";
import DemoSingleton from "./singleton";
import DemoFactory from "./factory";
let rayita = "=================";
console.log(rayita, "Observer", rayita);
DemoObserver();
console.log(rayita, "Adapter", rayita);
DemoAdapter();
console.log(rayita, "Singleton", rayita);
DemoSingleton();
console.log(rayita, "Factory", rayita);
DemoFactory();
